import "./globals.css";
import type { Metadata } from "next";
import CrtThemeController from "../src/components/CrtThemeController";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        {children}
        <CrtThemeController />
      </body>
    </html>
  );
}